name: Build vendor and push deploy branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader
      - name: Push to deploy branch (include vendor)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B deploy
          git add -A
          git add -f vendor/
          git commit -m "ci: build vendor for deploy" || echo "nothing to commit"
          git push -f origin deploy
